# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensagens_apl_gate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18mensagens_apl_gate.proto\"\x92\x01\n\x11MensagemAplicacao\x12-\n\x04tipo\x18\x01 \x01(\x0e\x32\x1f.MensagemAplicacao.TipoMensagem\x12\x0f\n\x07\x63omando\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\t\".\n\x0cTipoMensagem\x12\x11\n\rIDENTIFICADOR\x10\x00\x12\x0b\n\x07\x43OMANDO\x10\x01\"F\n\x06Objeto\x12\x10\n\x08\x65ndereco\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x0c\n\x04temp\x18\x04 \x01(\x05\"\x96\x01\n\x0fMensagemGateway\x12\x34\n\rtipo_resposta\x18\x01 \x01(\x0e\x32\x1d.MensagemGateway.TipoMensagem\x12\x17\n\x06objeto\x18\x02 \x03(\x0b\x32\x07.Objeto\"4\n\x0cTipoMensagem\x12\r\n\tATUALIZAR\x10\x00\x12\t\n\x05PEGAR\x10\x01\x12\n\n\x06LISTAR\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensagens_apl_gate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MENSAGEMAPLICACAO._serialized_start=29
  _MENSAGEMAPLICACAO._serialized_end=175
  _MENSAGEMAPLICACAO_TIPOMENSAGEM._serialized_start=129
  _MENSAGEMAPLICACAO_TIPOMENSAGEM._serialized_end=175
  _OBJETO._serialized_start=177
  _OBJETO._serialized_end=247
  _MENSAGEMGATEWAY._serialized_start=250
  _MENSAGEMGATEWAY._serialized_end=400
  _MENSAGEMGATEWAY_TIPOMENSAGEM._serialized_start=348
  _MENSAGEMGATEWAY_TIPOMENSAGEM._serialized_end=400
# @@protoc_insertion_point(module_scope)
